import {Inter} from "next/font/google";
import "./globals.css";
const inter = Inter({subsets: ["latin"]});
import Providers from "./Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      {/* <link
        href="https://vjs.zencdn.net/8.10.0/video-js.css"
        rel="stylesheet"
      /> */}
      <meta property="fc:frame" content="vNext" />
      <meta
        property="fc:frame:video"
        // content="https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8"
        content="https://far-from-frames.vercel.app/video.mp4"
      />
      <meta property="fc:frame:video:type" content="application/x-mpegURL" />
      <meta
        property="fc:frame:image"
        content="https://www.w3schools.com/w3images/mountains.jpg"
      />
      <meta
        property="og:image"
        content="https://www.w3schools.com/w3images/mountains.jpg"
      />
      <body className={inter.className}>
        <Providers
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </Providers>
      </body>
    </html>
  );
}
